apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: distributedtrainings.ahhuisg.com
spec:
  group: ahhuisg.com
  names:
    kind: DistributedTraining
    listKind: DistributedTrainingList
    plural: distributedtrainings
    singular: distributedtraining
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
