apiVersion: apps/v1
kind: Deployment
metadata:
  name: dt-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dt-operator
  template:
    metadata:
      labels:
        name: dt-operator
    spec:
      serviceAccountName: dt-operator
      containers:
        - name: dt-operator
          # Replace this with the built image name
          image: ahhuisg/dt-operator:0.0.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "dt-operator"
